[package]
name = "bleah"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
btleplug = "0.11"
crossterm = "0.27"
ratatui = "0.26"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
